services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    depends_on:
      - mariadb
    ports:
      - "8800:80"
    volumes:
      - "./public_html:/var/www/public_html:Z"
      - "./src:/var/www/src:Z"
      - "./php.ini:/usr/local/etc/php/php.ini:Z"
      - "./000-default.conf:/etc/apache2/sites-available/000-default.conf:Z"
    env_file:
      - ".env"
  mariadb:
    image: "mariadb:10.6.7"
    restart: "unless-stopped"
    ports:
      - "3306:3306"
    volumes:
      - "mariadb:/var/lib/mysql"
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql:Z"
    environment:
      MYSQL_ROOT_PASSWORD: "root-password"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    restart: "unless-stopped"
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "mariadb"
      MYSQL_ROOT_PASSWORD: "root-password"

volumes:
  mariadb:
